version: '3'

services:
  migrate:
    build: .
    container_name: 'migrate'
    command: >
      /bin/sh -c "
      python3 manage.py makemigrations --force-color --no-input -v 3 &&
      python3 manage.py makemigrations --merge --no-input -v 3 &&
      python3 manage.py migrate --force-color -v 3 &&
      python3 manage.py createsuperuser --noinput || true"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    volumes:
      - .:/app

  web:
    build: .
    container_name: 'django_web'
    restart: always
    command: gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - migrate
